# GitHub Actions workflow for deployment
name: Deploy k3s cluster

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.0"

      - name: Terraform Init
        working-directory: infra
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform apply \
            -auto-approve \
            -var "aws_region=us-east-1" \
            -var "instance_type=t3.micro"

      - name: Set up SSH key for kubeconfig retrieval
        run: |
          echo "${{ secrets.K3S_SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Retrieve kubeconfig from EC2
        run: |
          ip=$(terraform output -raw instance_public_ip)
          scp -o StrictHostKeyChecking=no -i id_rsa ec2-user@"$ip":/home/ec2-user/.kube/config ./kubeconfig

      - name: Deploy Hello World App
        run: |
          export KUBECONFIG=$(pwd)/kubeconfig
          kubectl apply -f ../hello-world.yaml

      - name: Validate Hello World Deployment
        run: |
          export KUBECONFIG=$(pwd)/kubeconfig
          kubectl rollout status deployment/hello-world
          kubectl get svc hello-world-service
          kubectl get pods
