# GitHub Actions workflow for deployment
name: Deploy k3s cluster

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.0"

      - name: Terraform Init
        working-directory: infra
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform apply -auto-approve -var "aws_region=us-east-1" -var "instance_type=t3.micro" || echo "Terraform apply failed, continuing for diagnostics."

      - name: Get EC2 Public IP via AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=k3s-node" "Name=instance-state-name,Values=running" --query "Reservations[*].Instances[*].InstanceId" --output text | head -n 1)
          ip=$(aws ec2 describe-instances --instance-ids "$INSTANCE_ID" --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
          echo "EC2 instance public IP: $ip"
          if [[ -z "$ip" ]]; then
            echo "ERROR: EC2 instance was not created or has no public IP. Skipping deployment steps."
            exit 0
          fi
          ping -c 3 $ip || { echo "ERROR: Instance is not reachable. Skipping deployment steps."; exit 0; }

      - name: Set up SSH key for kubeconfig retrieval
        if: success()
        run: |
          echo "${{ secrets.K3S_SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Retrieve kubeconfig from EC2
        if: success()
        run: |
          scp -o StrictHostKeyChecking=no -i id_rsa ec2-user@"$ip":/home/ec2-user/.kube/config ./kubeconfig || echo "Failed to retrieve kubeconfig, continuing."

      - name: Deploy Hello World App
        if: success()
        run: |
          export KUBECONFIG=$(pwd)/kubeconfig
          kubectl apply -f ../hello-world.yaml || echo "Failed to deploy Hello World app, continuing."

      - name: Validate Hello World Deployment
        if: success()
        run: |
          export KUBECONFIG=$(pwd)/kubeconfig
          kubectl rollout status deployment/hello-world || echo "Hello World deployment validation failed."
          kubectl get svc hello-world-service || echo "Failed to get Hello World service."
          kubectl get pods || echo "Failed to get pods."

      - name: Output Hello World Service External IP
        if: success()
        run: |
          export KUBECONFIG=$(pwd)/kubeconfig
          echo "Getting external IP for hello-world-service..."
          kubectl get svc hello-world-service -o json | jq -r '.status.loadBalancer.ingress[0].ip' || echo "No external IP assigned yet."
